Repository AjouCola/Cola_Back, pull requests merged in 2022-05, with the labels that each got.

#8 Hotfix/add cors setting
  build.gradle
  src/main/java/kr/or/cola/backend/user/config/WebConfig.java
  src/main/java/kr/or/cola/backend/user/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/or/cola/backend/user/config/auth/SecurityConfig.java
Labels: hotfix

#12 Feat/login success
  src/main/java/kr/or/cola/backend/user/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/or/cola/backend/user/config/auth/SecurityConfig.java
Labels: feat

#14 feat: redirect GUEST to signUp page
  src/main/java/kr/or/cola/backend/config/JpaConfig.java
  src/main/java/kr/or/cola/backend/config/SecurityConfig.java
  src/main/java/kr/or/cola/backend/config/WebConfig.java
  src/main/java/kr/or/cola/backend/security/LoginUser.java
  src/main/java/kr/or/cola/backend/security/LoginUserArgumentResolver.java
  src/main/java/kr/or/cola/backend/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/or/cola/backend/security/dto/OAuthAttributes.java
  src/main/java/kr/or/cola/backend/security/dto/SessionUser.java
  src/main/java/kr/or/cola/backend/user/UserController.java
  src/main/java/kr/or/cola/backend/user/UserService.java
  src/main/java/kr/or/cola/backend/user/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/or/cola/backend/user/domain/User.java
  src/main/java/kr/or/cola/backend/userinfo/UserInfoController.java
Labels: feat

#15 Fix/entity structure
  src/main/java/kr/or/cola/backend/config/SecurityConfig.java
  src/main/java/kr/or/cola/backend/config/WebConfig.java
  src/main/java/kr/or/cola/backend/oauth/LoginUser.java
  src/main/java/kr/or/cola/backend/oauth/LoginUserArgumentResolver.java
  src/main/java/kr/or/cola/backend/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/or/cola/backend/oauth/dto/OAuthAttributes.java
  src/main/java/kr/or/cola/backend/oauth/dto/SessionUser.java
  src/main/java/kr/or/cola/backend/post/domain/Post.java
  src/main/java/kr/or/cola/backend/post/domain/PostRepository.java
  src/main/java/kr/or/cola/backend/post/presentation/PostApiController.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostListResponseDto.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostResponseDto.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostSaveRequestDto.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostUpdateRequestDto.java
  src/main/java/kr/or/cola/backend/post/service/PostService.java
  src/main/java/kr/or/cola/backend/post/service/PostsService.java
  src/main/java/kr/or/cola/backend/user/UserService.java
  src/main/java/kr/or/cola/backend/user/domain/User.java
  src/main/java/kr/or/cola/backend/userinfo/domain/UserInfo.java
  src/main/java/kr/or/cola/backend/userinfo/domain/UserInfoRepository.java
  src/test/java/kr/or/cola/backend/post/domain/PostRepositoryTest.java
  src/test/java/kr/or/cola/backend/post/presentation/PostApiControllerTest.java
Labels: fix, refactor

#16 Fix/hiding redirect uri
  .gitignore
  src/main/java/kr/or/cola/backend/config/SecurityConfig.java
  src/main/java/kr/or/cola/backend/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/or/cola/backend/oauth/dto/OAuthAttributes.java
  src/main/resources/application.properties
Labels: feat, fix

#18 Dev
  .gitignore
  build.gradle
  src/main/java/kr/or/cola/backend/BackendApplication.java
  src/main/java/kr/or/cola/backend/auth/AuthToken.java
  src/main/java/kr/or/cola/backend/auth/AuthTokenController.java
  src/main/java/kr/or/cola/backend/auth/AuthTokenRepository.java
  src/main/java/kr/or/cola/backend/auth/AuthTokenService.java
  src/main/java/kr/or/cola/backend/common/SwaggerConfig.java
  src/main/java/kr/or/cola/backend/config/JpaConfig.java
  src/main/java/kr/or/cola/backend/config/SecurityConfig.java
  src/main/java/kr/or/cola/backend/config/WebConfig.java
  src/main/java/kr/or/cola/backend/exception/BadRequestException.java
  src/main/java/kr/or/cola/backend/exception/EnvironmentCode.java
  src/main/java/kr/or/cola/backend/oauth/LoginUser.java
  src/main/java/kr/or/cola/backend/oauth/LoginUserArgumentResolver.java
  src/main/java/kr/or/cola/backend/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/or/cola/backend/oauth/dto/OAuthAttributes.java
  src/main/java/kr/or/cola/backend/oauth/dto/SessionUser.java
  src/main/java/kr/or/cola/backend/post/domain/Post.java
  src/main/java/kr/or/cola/backend/post/domain/PostRepository.java
  src/main/java/kr/or/cola/backend/post/presentation/PostApiController.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostListResponseDto.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostResponseDto.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostSaveRequestDto.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostUpdateRequestDto.java
  src/main/java/kr/or/cola/backend/post/service/PostService.java
  src/main/java/kr/or/cola/backend/user/UserController.java
  src/main/java/kr/or/cola/backend/user/UserService.java
  src/main/java/kr/or/cola/backend/user/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/or/cola/backend/user/config/auth/SecurityConfig.java
  src/main/java/kr/or/cola/backend/user/domain/User.java
  src/main/java/kr/or/cola/backend/userinfo/UserInfoController.java
  src/main/java/kr/or/cola/backend/util/CustomMailSender.java
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/test/java/kr/or/cola/backend/BackendApplicationTests.java
  src/test/java/kr/or/cola/backend/post/domain/PostRepositoryTest.java
  src/test/java/kr/or/cola/backend/post/presentation/PostApiControllerTest.java
Labels: feat, fix, refactor

#20 Feature/comment controller
  src/main/java/kr/or/cola/backend/comment/controller/CommentController.java
  src/main/java/kr/or/cola/backend/comment/domain/Comment.java
  src/main/java/kr/or/cola/backend/comment/domain/CommentRepository.java
  src/main/java/kr/or/cola/backend/comment/presentation/CommentController.java
  src/main/java/kr/or/cola/backend/comment/presentation/dto/CommentCreateOrUpdateRequestDto.java
  src/main/java/kr/or/cola/backend/comment/presentation/dto/CommentResponseDto.java
  src/main/java/kr/or/cola/backend/comment/service/CommentService.java
  src/main/java/kr/or/cola/backend/post/presentation/PostController.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostResponseDto.java
  src/main/java/kr/or/cola/backend/post/service/PostService.java
Labels: feat, fix

#22 Feature/s3 controller
  build.gradle
  src/main/java/kr/or/cola/backend/aws/presentation/AwsS3Controller.java
  src/main/java/kr/or/cola/backend/aws/service/AwsS3Service.java
  src/main/java/kr/or/cola/backend/common/presentation/RootController.java
  src/main/java/kr/or/cola/backend/config/AwsS3Config.java
  src/main/resources/application.properties
Labels: feat, fix

#30 fix: change createComment controller response
  src/main/java/kr/or/cola/backend/comment/presentation/CommentController.java
  src/main/java/kr/or/cola/backend/comment/service/CommentService.java
Labels: fix

#31 feat: add signUp API
  src/main/java/kr/or/cola/backend/auth/AuthTokenController.java
  src/main/java/kr/or/cola/backend/auth/dto/SignUpRequestDto.java
  src/main/java/kr/or/cola/backend/user/UserService.java
  src/main/java/kr/or/cola/backend/user/domain/Major.java
  src/main/java/kr/or/cola/backend/user/domain/User.java
  src/main/java/kr/or/cola/backend/user/domain/UserRepository.java
  src/main/java/kr/or/cola/backend/user/presentation/UserController.java
Labels: feat

#32 Feat/add get user info controller
  src/main/java/kr/or/cola/backend/user/UserService.java
  src/main/java/kr/or/cola/backend/user/presentation/UserController.java
Labels: feat

#33 Feat/add get post list controller
  src/main/java/kr/or/cola/backend/auth/AuthTokenController.java
  src/main/java/kr/or/cola/backend/common/ResponseWithPagination.java
  src/main/java/kr/or/cola/backend/post/presentation/PostController.java
  src/main/java/kr/or/cola/backend/post/service/PostService.java
  src/main/resources/application.properties
  src/test/java/kr/or/cola/backend/post/presentation/PostControllerTest.java
  src/test/java/kr/or/cola/backend/post/service/PostServiceTest.java
Labels: feat, test

#37 Fix/get post list controller
  src/main/java/kr/or/cola/backend/post/domain/Post.java
  src/main/java/kr/or/cola/backend/post/domain/PostRepository.java
  src/main/java/kr/or/cola/backend/post/domain/PostType.java
  src/main/java/kr/or/cola/backend/post/presentation/PostController.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/SimplePostResponseDto.java
  src/main/java/kr/or/cola/backend/post/service/PostService.java
  src/test/java/kr/or/cola/backend/post/presentation/PostApiControllerTest.java
  src/test/java/kr/or/cola/backend/post/presentation/PostControllerTest.java
  src/test/java/kr/or/cola/backend/post/service/PostServiceTest.java
Labels: fix

#36 Fix/update user entity
  src/main/java/kr/or/cola/backend/user/UserService.java
  src/main/java/kr/or/cola/backend/user/domain/User.java
Labels: fix

#34 feat: add github User
  src/main/java/kr/or/cola/backend/config/SecurityConfig.java
  src/main/java/kr/or/cola/backend/oauth/dto/OAuthAttributes.java
Labels: feat

#39 Feat/add tag api
  src/main/java/kr/or/cola/backend/aws/presentation/AwsS3Controller.java
  src/main/java/kr/or/cola/backend/aws/service/AwsS3Service.java
  src/main/java/kr/or/cola/backend/comment/domain/Comment.java
  src/main/java/kr/or/cola/backend/comment/service/CommentService.java
  src/main/java/kr/or/cola/backend/post/post/domain/Post.java
  src/main/java/kr/or/cola/backend/post/post/domain/PostRepository.java
  src/main/java/kr/or/cola/backend/post/post/domain/PostType.java
  src/main/java/kr/or/cola/backend/post/post/presentation/PostController.java
  src/main/java/kr/or/cola/backend/post/post/presentation/dto/PostCreateOrUpdateRequestDto.java
  src/main/java/kr/or/cola/backend/post/post/presentation/dto/PostResponseDto.java
  src/main/java/kr/or/cola/backend/post/post/presentation/dto/SimplePostResponseDto.java
  src/main/java/kr/or/cola/backend/post/post/service/PostService.java
  src/main/java/kr/or/cola/backend/post/post_tag/domain/PostTag.java
  src/main/java/kr/or/cola/backend/post/post_tag/domain/PostTagRepository.java
  src/main/java/kr/or/cola/backend/post/post_tag/service/PostTagService.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostCreateRequestDto.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostResponseDto.java
  src/main/java/kr/or/cola/backend/post/presentation/dto/PostUpdateRequestDto.java
  src/main/java/kr/or/cola/backend/post/tag/domain/Tag.java
  src/main/java/kr/or/cola/backend/post/tag/domain/TagRepository.java
  src/main/java/kr/or/cola/backend/post/tag/service/TagService.java
Labels: feat

#40 feat: add post type to postResponseDto
  src/main/java/kr/or/cola/backend/post/post/presentation/dto/PostResponseDto.java
  src/main/java/kr/or/cola/backend/post/post/service/PostService.java
  src/main/java/kr/or/cola/backend/post/post_tag/domain/PostTagRepository.java
  src/main/java/kr/or/cola/backend/post/post_tag/service/PostTagService.java
  src/main/java/kr/or/cola/backend/post/tag/service/TagService.java
  src/main/resources/application.properties
Labels: feat

#41 Feat/add update user info controller
  src/main/java/kr/or/cola/backend/auth/AuthTokenController.java
  src/main/java/kr/or/cola/backend/user/UserService.java
  src/main/java/kr/or/cola/backend/user/domain/User.java
  src/main/java/kr/or/cola/backend/user/presentation/UserController.java
  src/main/java/kr/or/cola/backend/user/presentation/dto/SimpleUserResponseDto.java
  src/main/java/kr/or/cola/backend/user/presentation/dto/UserResponseDto.java
  src/main/java/kr/or/cola/backend/user/presentation/dto/UserUpdateRequestDto.java
Labels: feat

#23 feat: todo
  src/main/java/kr/or/cola/backend/todo/TodoController.java
  src/main/java/kr/or/cola/backend/todo/TodoService.java
  src/main/java/kr/or/cola/backend/todo/dto/TodoFolderResponseDto.java
  src/main/java/kr/or/cola/backend/todo/dto/TodoResponseDto.java
  src/main/java/kr/or/cola/backend/todo/folder/FolderController.java
  src/main/java/kr/or/cola/backend/todo/folder/FolderService.java
  src/main/java/kr/or/cola/backend/todo/folder/domain/Folder.java
  src/main/java/kr/or/cola/backend/todo/folder/domain/FolderRepository.java
  src/main/java/kr/or/cola/backend/todo/folder/dto/FolderResponseDto.java
  src/main/java/kr/or/cola/backend/todo/folder/dto/FolderUpdateRequestDto.java
  src/main/java/kr/or/cola/backend/todo/folder/dto/ItemsResponseDto.java
  src/main/java/kr/or/cola/backend/todo/item/ItemController.java
  src/main/java/kr/or/cola/backend/todo/item/ItemService.java
  src/main/java/kr/or/cola/backend/todo/item/domain/Item.java
  src/main/java/kr/or/cola/backend/todo/item/domain/ItemRepository.java
  src/main/java/kr/or/cola/backend/todo/item/dto/ItemCreateOrUpdateRequestDto.java
  src/main/java/kr/or/cola/backend/todo/item/dto/ItemDateResponseDto.java
  src/main/java/kr/or/cola/backend/todo/item/dto/ItemDto.java
  src/main/java/kr/or/cola/backend/user/UserService.java
  src/main/java/kr/or/cola/backend/user/domain/User.java
Labels: feat

#42 fix: fix updateUserProfile service
  src/main/java/kr/or/cola/backend/aws/presentation/AwsS3Controller.java
  src/main/java/kr/or/cola/backend/aws/service/AwsS3Service.java
  src/main/java/kr/or/cola/backend/user/UserService.java
  src/main/java/kr/or/cola/backend/user/domain/User.java
  src/main/java/kr/or/cola/backend/user/presentation/UserController.java
Labels: fix

#43 Feat/add post thumbnail and preview
  src/main/java/kr/or/cola/backend/aws/presentation/AwsS3Controller.java
  src/main/java/kr/or/cola/backend/aws/service/AwsS3Service.java
  src/main/java/kr/or/cola/backend/post/post/domain/Post.java
  src/main/java/kr/or/cola/backend/post/post/presentation/PostController.java
  src/main/java/kr/or/cola/backend/post/post/presentation/dto/PostCreateOrUpdateRequestDto.java
  src/main/java/kr/or/cola/backend/post/post/service/PostService.java
  src/main/java/kr/or/cola/backend/todo/folder/FolderController.java
  src/main/java/kr/or/cola/backend/todo/folder/dto/FolderUpdateRequestDto.java
  src/main/java/kr/or/cola/backend/user/UserService.java
Labels: feat, fix
